name: isolate_agents
description: Agents are state that lives on a background isolate.
version: 0.2.0
repository: https://github.com/gaaclarke/agents

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.5
